/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestNotWorkingCssRouteImport } from './routes/test.not-working-css'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNotWorkingCssRoute = TestNotWorkingCssRouteImport.update({
  id: '/test/not-working-css',
  path: '/test/not-working-css',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/not-working-css': typeof TestNotWorkingCssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/not-working-css': typeof TestNotWorkingCssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test/not-working-css': typeof TestNotWorkingCssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test/not-working-css'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test/not-working-css'
  id: '__root__' | '/' | '/test/not-working-css'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestNotWorkingCssRoute: typeof TestNotWorkingCssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/not-working-css': {
      id: '/test/not-working-css'
      path: '/test/not-working-css'
      fullPath: '/test/not-working-css'
      preLoaderRoute: typeof TestNotWorkingCssRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestNotWorkingCssRoute: TestNotWorkingCssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
